language: ruby
dist: trusty
sudo: false
cache: bundler
bundler_args: --without tools
script:
  - bundle exec rake
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - jruby-9.1.5.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: rbx-3
addons:
  code_climate:
    repo_token: 2c92f1dc6b512f11d06153bcf2f3f5b507af6faa95b3319f559bae1a6bcb2c1a
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
