language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - rbx-2
  - jruby-9000
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
addons:
  code_climate:
    repo_token: 2c92f1dc6b512f11d06153bcf2f3f5b507af6faa95b3319f559bae1a6bcb2c1a
