language: ruby
sudo: false
cache: bundler
bundler_args: --without tools
rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - rbx-2
  - jruby-9000
  - ruby-head
  - jruby-head
before_install:
  - gem update bundler
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
addons:
  code_climate:
    repo_token: 2c92f1dc6b512f11d06153bcf2f3f5b507af6faa95b3319f559bae1a6bcb2c1a
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
